apiVersion: apps/v1 kind: Deployment metadata: name: my-app-deployment spec: replicas: 1 selector: matchLabels: app: my-app 
  template:
<<<<<<< HEAD
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: rakeshacr.azurecr.io/myflaskapp:latest  # Replace rakeshacr with your actual ACR name
        ports:
        - containerPort: 5000
=======
    metadata: labels: app: my-app spec: containers: - name: my-app image: rakeshacr.azurecr.io/myflaskapp:latest # Replace 
        rakeshacr with your actual ACR name ports: - containerPort: 5000
>>>>>>> afd6aa5 (Updated deployment.yaml with the correct image path)
