apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: azurek8sdemoacr.azurecr.io/myapp:v1  # This will be updated dynamically
        ports:
        - containerPort: 5000
